-- Inserção de 60 endereços de fornecedores
INSERT INTO endereco_fornecedor (ID_endereco, tipo, logradouro, bairro, cidade, estado) VALUES
(1, 'Comercial', 'Rua das Palmeiras', 'Centro', 'Rio de Janeiro', 'RJ'),
(2, 'Industrial', 'Av. Brasil', 'Zona Norte', 'São Paulo', 'SP'),
(3, 'Residencial', 'Rua das Acácias', 'Jardins', 'Belo Horizonte', 'MG'),
(4, 'Comercial', 'Rua 7 de Setembro', 'Comércio', 'Salvador', 'BA'),
(5, 'Comercial', 'Av. Independência', 'Centro', 'Porto Alegre', 'RS'),
(6, 'Comercial', 'Rua Floriano Peixoto', 'Centro', 'Curitiba', 'PR'),
(7, 'Industrial', 'Av. das Indústrias', 'Distrito Industrial', 'Manaus', 'AM'),
(8, 'Residencial', 'Rua São João', 'Vila Nova', 'Fortaleza', 'CE'),
(9, 'Comercial', 'Av. Paulista', 'Bela Vista', 'São Paulo', 'SP'),
(10, 'Comercial', 'Rua dos Andradas', 'Centro', 'Porto Alegre', 'RS'),
(11, 'Comercial', 'Av. Afonso Pena', 'Funcionários', 'Belo Horizonte', 'MG'),
(12, 'Comercial', 'Rua XV de Novembro', 'Centro', 'Curitiba', 'PR'),
(13, 'Residencial', 'Rua das Rosas', 'Jardim das Flores', 'Campinas', 'SP'),
(14, 'Industrial', 'Av. Perimetral', 'Distrito Norte', 'Belém', 'PA'),
(15, 'Comercial', 'Rua da Paz', 'Centro', 'Vitória', 'ES'),
(16, 'Residencial', 'Rua Ipê Amarelo', 'Jardim Primavera', 'Niterói', 'RJ'),
(17, 'Comercial', 'Av. Rio Branco', 'Centro', 'Rio de Janeiro', 'RJ'),
(18, 'Comercial', 'Rua João Pessoa', 'Centro', 'Joinville', 'SC'),
(19, 'Industrial', 'Av. Sete Lagoas', 'Industrial', 'Contagem', 'MG'),
(20, 'Residencial', 'Rua das Oliveiras', 'Monte Verde', 'Maceió', 'AL'),
(21, 'Comercial', 'Rua Dom Pedro II', 'Bairro Novo', 'São Luís', 'MA'),
(22, 'Industrial', 'Av. do Café', 'Distrito Café', 'Ribeirão Preto', 'SP'),
(23, 'Comercial', 'Rua Chile', 'Centro', 'Salvador', 'BA'),
(24, 'Residencial', 'Rua da Aurora', 'Boa Vista', 'Recife', 'PE'),
(25, 'Comercial', 'Av. Beira Mar', 'Praia de Iracema', 'Fortaleza', 'CE'),
(26, 'Residencial', 'Rua das Bromélias', 'Santa Rosa', 'Niterói', 'RJ'),
(27, 'Comercial', 'Rua Visconde de Inhaúma', 'Centro', 'Rio de Janeiro', 'RJ'),
(28, 'Comercial', 'Rua Carlos Gomes', 'Brotas', 'Salvador', 'BA'),
(29, 'Comercial', 'Rua Barão do Rio Branco', 'Centro', 'Blumenau', 'SC'),
(30, 'Residencial', 'Rua Pequiá', 'Vila Madalena', 'São Paulo', 'SP'),
(31, 'Industrial', 'Av. do Trabalho', 'Indústrias', 'Caxias do Sul', 'RS'),
(32, 'Comercial', 'Rua Marquês de Abrantes', 'Flamengo', 'Rio de Janeiro', 'RJ'),
(33, 'Comercial', 'Av. Getúlio Vargas', 'Centro', 'Uberlândia', 'MG'),
(34, 'Comercial', 'Rua Frei Caneca', 'República', 'São Paulo', 'SP'),
(35, 'Residencial', 'Rua Cedro', 'Tijuca', 'Rio de Janeiro', 'RJ'),
(36, 'Comercial', 'Av. Norte-Sul', 'Centro', 'Aracaju', 'SE'),
(37, 'Industrial', 'Rua das Máquinas', 'Polo Industrial', 'Diadema', 'SP'),
(38, 'Comercial', 'Av. Atlântica', 'Copacabana', 'Rio de Janeiro', 'RJ'),
(39, 'Residencial', 'Rua dos Pinhais', 'Santa Tereza', 'Belo Horizonte', 'MG'),
(40, 'Comercial', 'Rua Senador Pompeu', 'Centro', 'Fortaleza', 'CE'),
(41, 'Residencial', 'Rua Flor de Lótus', 'Jardim América', 'Goiânia', 'GO'),
(42, 'Comercial', 'Av. Presidente Vargas', 'Centro', 'Rio de Janeiro', 'RJ'),
(43, 'Comercial', 'Rua da Assembleia', 'Centro', 'Rio de Janeiro', 'RJ'),
(44, 'Comercial', 'Rua das Gaivotas', 'Praia Grande', 'Santos', 'SP'),
(45, 'Residencial', 'Rua Laranjeiras', 'São Francisco', 'Niterói', 'RJ'),
(46, 'Industrial', 'Rua Fundição', 'Zona Industrial', 'Contagem', 'MG'),
(47, 'Comercial', 'Av. Amazonas', 'Centro', 'Belo Horizonte', 'MG'),
(48, 'Residencial', 'Rua do Limoeiro', 'Centro', 'Recife', 'PE'),
(49, 'Comercial', 'Rua Bento Gonçalves', 'Centro', 'Canoas', 'RS'),
(50, 'Industrial', 'Rua da Produção', 'Indústrias', 'Joinville', 'SC'),
(51, 'Comercial', 'Rua das Acácias', 'Barra', 'Salvador', 'BA'),
(52, 'Comercial', 'Rua do Comércio', 'Centro', 'Cuiabá', 'MT'),
(53, 'Residencial', 'Rua Dália', 'Jardim das Acácias', 'São José', 'SC'),
(54, 'Comercial', 'Rua Santo Antônio', 'Centro', 'João Pessoa', 'PB'),
(55, 'Residencial', 'Rua das Figueiras', 'Jardim Paulista', 'São Paulo', 'SP'),
(56, 'Comercial', 'Rua Maranhão', 'Centro', 'Campo Grande', 'MS'),
(57, 'Comercial', 'Rua dos Coqueiros', 'Boa Viagem', 'Recife', 'PE'),
(58, 'Comercial', 'Rua das Águas', 'Centro', 'Foz do Iguaçu', 'PR'),
(59, 'Residencial', 'Rua Pitangueiras', 'Tambaú', 'João Pessoa', 'PB'),
(60, 'Industrial', 'Av. das Fábricas', 'Distrito Sul', 'Campinas', 'SP');